## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()


City_ID          City Country  Max Temp Current Description    Lat     Lng  \
0        1    Butaritari      KI     81.25     overcast clouds   3.07  172.79   
1        7  Puerto Ayora      EC     75.20       broken clouds  -0.74  -90.35   
2        9    Vila Velha      BR     79.00    scattered clouds -20.33  -40.29   
3       11       Gouyave      GD     86.00       broken clouds  12.16  -61.73   
4       16     Zacualpan      MX     80.60           clear sky  21.25 -105.17   

                  Hotel Name  
0         Isles Sunset Lodge  
1  Finch Bay Galapagos Hotel  
2       Hotel Vitória Palace  
3            Rumboat Retreat  
4            La Colorada B&B

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd> 
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure

fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"] == "Chongwe"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Chongwe"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Mutoko"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Quelimane"]
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Nampula"]

In [6]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy()[0],vacation_start["Lng"].to_numpy()[0]
end = vacation_end[["Lat", "Lng"]].to_numpy()[0]
stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()[0]
stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()[0]
stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()[0]
start

(-15.33, 28.68)

In [7]:
#Cairns Lat and Lng
stop1

array([-17.4 ,  32.23])

In [8]:
#Biloela Lat and Lng
stop2

array([-17.88,  36.89])

In [9]:
#Hervey Bay Lat and Lng
stop3

array([-15.12,  39.27])

In [10]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()

iteniary = gmaps.directions_layer(
start, end, waypoints = [stop1, stop2, stop3], travel_mode= "DRIVING")
fig.add_layer(iteniary)
fig




Figure(layout=FigureLayout(height='420px'))

In [11]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_end, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID       City Country  Max Temp Current Description    Lat    Lng  \
0      138    Chongwe      ZM     79.38           clear sky -15.33  28.68   
1      138    Chongwe      ZM     79.38           clear sky -15.33  28.68   
2      297     Mutoko      ZW     81.61       broken clouds -17.40  32.23   
3       84  Quelimane      MZ     84.20           clear sky -17.88  36.89   
4      451    Nampula      MZ     84.00           clear sky -15.12  39.27   

          Hotel Name  
0            Farm KS  
1            Farm KS  
2  Nyamakwere Lodges  
3     Hotel Flamingo  
4  Tacab Residencial

In [12]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd> 
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [13]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
# fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))